import { CSSProperties } from "react";

type Styles = { [key: string]: CSSProperties };

const styles: Styles = {
  container: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#f9fafb",
  },
  pdfSection: {
    width: "50%",
    backgroundColor: "white",
    borderRight: "1px solid #e5e7eb",
    display: "flex",
    flexDirection: "column",
  },
  pdfHeader: {
    padding: "1rem",
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "white",
  },
  pdfHeaderTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "0.5rem",
  },
  pdfHeaderTitle: {
    fontSize: "1.125rem",
    color: "#1f2937",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    margin: 0,
  },
  clearBtn: {
    background: "none",
    border: "none",
    color: "#dc2626",
    cursor: "pointer",
    fontSize: "0.875rem",
    padding: "0.25rem 0.5rem",
    borderRadius: "0.25rem",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  pdfInfo: {
    fontSize: "0.875rem",
    color: "#6b7280",
    marginTop: "0.5rem",
  },
  filename: {
    fontWeight: 500,
    marginBottom: "0.5rem",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  pageInfo: {
    fontSize: "0.75rem",
  },
  pageNavigation: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  navBtn: {
    background: "none",
    border: "1px solid #d1d5db",
    borderRadius: "0.25rem",
    padding: "0.25rem",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    color: "#6b7280",
  },
  navBtnDisabled: {
    background: "none",
    border: "1px solid #e5e7eb",
    borderRadius: "0.25rem",
    padding: "0.25rem",
    cursor: "not-allowed",
    display: "flex",
    alignItems: "center",
    color: "#d1d5db",
  },
  pdfContent: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem",
    backgroundColor: "#f9fafb",
    overflowY: "auto",
  },
  uploadPrompt: {
    textAlign: "center",
  },
  uploadIcon: {
    width: "4rem",
    height: "4rem",
    backgroundColor: "#f3e8ff",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 1rem",
    color: "#9333ea",
  },
  uploadTitle: {
    fontSize: "1.125rem",
    color: "#1f2937",
    marginBottom: "0.5rem",
  },
  uploadText: {
    fontSize: "0.875rem",
    color: "#6b7280",
    marginBottom: "1.5rem",
  },
  hiddenInput: {
    display: "none",
  },
  uploadBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.75rem 1.5rem",
    backgroundColor: "#9333ea",
    color: "white",
    border: "none",
    borderRadius: "0.5rem",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: 500,
  },
  uploadingContainer: {
    width: "100%",
    maxWidth: "28rem",
  },
  progressHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "0.5rem",
  },
  progressLabel: {
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "#9333ea",
  },
  progressBar: {
    width: "100%",
    height: "0.5rem",
    backgroundColor: "#e5e7eb",
    borderRadius: "9999px",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    width: "100%",
    backgroundColor: "#9333ea",
    borderRadius: "9999px",
    animation: "pulse 1.5s ease-in-out infinite",
  },
  progressText: {
    fontSize: "0.75rem",
    color: "#6b7280",
    marginTop: "0.5rem",
    textAlign: "center",
  },
  pdfViewer: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  loadingPdf: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1rem",
    padding: "2rem",
  },
  chatSection: {
    width: "50%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "white",
  },
  chatHeader: {
    padding: "1rem",
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "white",
  },
  chatHeaderTitle: {
    fontSize: "1.125rem",
    color: "#1f2937",
    marginBottom: "0.25rem",
    margin: 0,
  },
  chatHeaderText: {
    fontSize: "0.875rem",
    color: "#6b7280",
    margin: 0,
  },
  chatMessages: {
    flex: 1,
    overflowY: "auto",
    padding: "1.5rem",
  },
  chatEmpty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    textAlign: "center",
    color: "#9ca3af",
  },
  chatEmptyContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  chatEmptyIcon: {
    width: "4rem",
    height: "4rem",
    opacity: 0.5,
    marginBottom: "1rem",
  },
  messageUser: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: "1rem",
  },
  messageAssistant: {
    display: "flex",
    justifyContent: "flex-start",
    marginBottom: "1rem",
  },
  messageContentUser: {
    maxWidth: "80%",
    padding: "0.75rem 1rem",
    borderRadius: "1rem",
    backgroundColor: "#9333ea",
    color: "white",
    borderBottomRightRadius: "0.25rem",
  },
  messageContentAssistant: {
    maxWidth: "80%",
    padding: "0.75rem 1rem",
    borderRadius: "1rem",
    backgroundColor: "#f3f4f6",
    color: "#1f2937",
    borderBottomLeftRadius: "0.25rem",
  },
  messageText: {
    fontSize: "0.875rem",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    margin: 0,
  },
  citations: {
    marginTop: "0.75rem",
    paddingTop: "0.75rem",
    borderTop: "1px solid #e5e7eb",
  },
  citationBtn: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.5rem",
    width: "100%",
    textAlign: "left",
    padding: "0.5rem",
    background: "none",
    border: "none",
    borderRadius: "0.5rem",
    cursor: "pointer",
    marginBottom: "0.5rem",
  },
  citationIcon: {
    width: "1rem",
    height: "1rem",
    color: "#9333ea",
    flexShrink: 0,
    marginTop: "0.125rem",
  },
  citationContent: {
    flex: 1,
    minWidth: 0,
  },
  citationPage: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#9333ea",
    marginBottom: "0.125rem",
  },
  citationSnippet: {
    fontSize: "0.75rem",
    color: "#6b7280",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  loader: {
    width: "1.25rem",
    height: "1.25rem",
    border: "2px solid #e5e7eb",
    borderTopColor: "#9333ea",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  loaderSmall: {
    width: "1.25rem",
    height: "1.25rem",
    border: "2px solid #fff",
    borderTopColor: "transparent",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  chatInputContainer: {
    padding: "1rem",
    borderTop: "1px solid #e5e7eb",
    backgroundColor: "white",
  },
  chatInputWrapper: {
    display: "flex",
    gap: "0.5rem",
  },
  chatInput: {
    flex: 1,
    padding: "0.75rem 1rem",
    border: "1px solid #d1d5db",
    borderRadius: "0.75rem",
    fontSize: "0.875rem",
    outline: "none",
  },
  chatInputDisabled: {
    flex: 1,
    padding: "0.75rem 1rem",
    border: "1px solid #d1d5db",
    borderRadius: "0.75rem",
    fontSize: "0.875rem",
    outline: "none",
    backgroundColor: "#f9fafb",
    color: "#9ca3af",
    cursor: "not-allowed",
  },
  sendBtn: {
    padding: "0.75rem 1.5rem",
    backgroundColor: "#9333ea",
    color: "white",
    border: "none",
    borderRadius: "0.75rem",
    cursor: "pointer",
    fontSize: "0.875rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  sendBtnDisabled: {
    padding: "0.75rem 1.5rem",
    backgroundColor: "#d1d5db",
    color: "white",
    border: "none",
    borderRadius: "0.75rem",
    cursor: "not-allowed",
    fontSize: "0.875rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
};
export default styles;
